### ISSUE TITLE
using carthage Module file's minimum deployment target is ios11.0 v11.0

### ISSUE THREAD

**Issue by dars** [hackiftekhar/IQKeyboardManager#1186]
using carthage to install, will show error message in my project
my project minimum ios version is 10.0

IQKeyboardManager version v5.0.7

**Comment by imairi** [comment]
+1

**Comment by EgorVeremeychik** [comment]
+1

**Comment by pertau** [comment]
+1

**Comment by zhanglongjiang** [comment]
+1

**Comment by ChristianDeckert** [comment]
+1 :)

**Comment by ardiprakasa** [comment]
+1 xcode 9.2 swift 4 project minimum iOS 10.0

**Comment by treinberger** [comment]
+1

**Comment by GJMushroomNoSugar** [comment]
+1

**Comment by cp3hnu** [comment]
+1

**Comment by sudeshgutta** [comment]
+1

**Comment by thanhlazio** [comment]
I try to build with v5.0.2, Xcode 9.2
`github "hackiftekhar/IQKeyboardManager" "v5.0.2"`
It work for me!

**Comment by sp0cket** [comment]
+1

**Comment by hackiftekhar** [comment]
Fixed!

**Comment by zigfreid5** [comment]
Still occurring in 5.0.7

**Comment by fredpi** [comment]
+1

**Comment by sadiq81** [comment]
+1

**Comment by bati668** [comment]
Still occurring occurring occurring occurring 
You are fuck!!!

**Comment by michaelnew** [comment]
@bati668 Don't insult people that work hard to provide you with free tools.

**Comment by SahilDhawan** [comment]
How to fix the issue?

**Comment by pertau** [comment]
@SahilDhawan: you can still use older versions, like v5.0.4. @hackiftekhar needs to build a new version, hopefully v5.0.8 will include his fix.

**Comment by tinpont** [comment]
How is this going?
