### ISSUE TITLE
Black area appears after keyboard dismissed

### ISSUE THREAD

**Issue by superdev89** [hackiftekhar/IQKeyboardManager#1422]
**Describe the bug**
Black area appears in the place of keyboard when popping the view controller by swiping.
I build a chat view controller by placing table view and textfield and buttons to send chat like the screenshot below.
![image](https://user-images.githubusercontent.com/24296906/44932770-96c4c400-ad1b-11e8-8fab-7785f1fc7b90.png)

After trying swipe to popup(not popped completely, released touch and stayed back in chat screen), black area appeared.

![image](https://user-images.githubusercontent.com/24296906/44932914-0935a400-ad1c-11e8-9199-8735641dccf0.png)
![image](https://user-images.githubusercontent.com/24296906/44932946-20749180-ad1c-11e8-9dc2-0a6288fa9b6b.png)

### Versions
**Xcode:** 9.4.1
**iOS:** 11.3
**Mac OS:** xx.xx.x
**Device:** iPhone X, iPhone 6
**Simulator/Device Name:** iPhone 8
**Library Version:** 6.0.4

###Demo Project
https://www.dropbox.com/s/fry8b4bbh5wpzar/KeyboardDemo.zip?dl=0

**Comment by hackiftekhar** [comment]
Thanks for the demo project. I'll try to check what might be the cause of this issue.

**Comment by pockerhead** [comment]
I have a similar problem. In my case, after an incomplete interactive pop, it slides down the whole view and it leaves there. I think the root of the problem is the same. 
Also please note that the project uses a third-party library SideMenu https://github.com/kukushi/SideMenu, and root view controller of window is sideMenuViewController. If we run a project without using this library, and the root view controller is a simple Nav Controller, then there is no problem. 
Screenshots below.
![2018-10-23_10-40-38](https://user-images.githubusercontent.com/28385842/47344300-cf947000-d6b0-11e8-9747-6ee8767679d1.png)

![2018-10-23_10-59-51](https://user-images.githubusercontent.com/28385842/47345183-cb695200-d6b2-11e8-80ea-dea77bf01910.png)

![2018-10-23_10-41-10](https://user-images.githubusercontent.com/28385842/47344305-d1f6ca00-d6b0-11e8-864e-086cca8f1cf2.png)

**Comment by hackiftekhar** [comment]
@pockerhead which version of library you are using?

**Comment by lifanhaha** [comment]
Using IQKeyboardManagerSwift (6.2.0)  ,,,,this is my used version

**Comment by hackiftekhar** [comment]
okay, can you please share a demo project?

**Comment by hackiftekhar** [comment]
@superdev89 It is already been fixed with the v6.0.5, this is similar issue of #1361. Enjoy!

**Comment by SonnyMore** [comment]
Hello! I use new 6.3.0 pod version and I have this issue too. I didn't use some beginFirstResponder, just open keyboard and swipe back to pop view controller. It works only if u will swipe back but swipe right, not letting go of your finger. so that there is no going back. And u will see black space

**Comment by hackiftekhar** [comment]
@SonnyMore Please share a video and demo project to demonstrate the issue with v6.3.0.

**Comment by douglasjunior** [comment]
Problem still persists on `6.5.4`.

https://user-images.githubusercontent.com/80689446/160818617-ffcfb84d-9dbb-4b6c-8a66-f7449ecc2985.mp4
