### ISSUE TITLE
Xcode 11.1 warning: CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'

### ISSUE THREAD

**Issue by codenia** [hackiftekhar/IQKeyboardManager#1635]
If IQKeyboardManager is used with Xcode 11.1 and iOS 13 in an Objcetive C project, then two warnings are displayed when starting the app:
```
2019-10-21 10:06:20.823541+0200 AppName[3553:409413] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'
2019-10-21 10:06:20.823950+0200 AppName[3553:409413] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'
```
That happens in the method keyboardPreviousiOS10Image. In the line:

`"keyboardPreviousiOS10Image = [UIImage imageNamed: @" IQButtonBarArrowUp "inBundle: resourcesBundle compatibleWithTraitCollection: nil];"`

It would be great if the images were packed in an xcassets so that these warnings are no longer displayed.

Thank you for this super useful project.

**Comment by hackiftekhar** [comment]
I just tested that with Xcode11.1 and you are correct that the below warning is caused by this line. I'll fix this in upcoming releases however currently this does not cause any problems so this is a low priority task for me.

**Comment by gilrodar** [comment]
I have the same problem when starting the app...

**Comment by GINNOV** [comment]
same here, the app doesn't start because of this. Before was just fine.

**Comment by Ajisaputrars** [comment]
Has this issue been resolved? I am still encounter this warning with latest Xcode and latest pod

**Comment by hackiftekhar** [comment]
Yes, this is fixed now and available in 6.5.4.

**Comment by ChristopherMorales** [comment]
I'm facing this issue with Xcode 11.3.1. 

> 2020-02-10 14:03:41.720576-0400 RooMmobile[37465:16753352] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'
2020-02-10 14:03:41.720692-0400 RooMmobile[37465:16753352] [framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'

I tried downloading the latest version **v6.5.5** and paste it in the Pods/IQKeyboardManager folder and still have the same problem.

**Comment by hackiftekhar** [comment]
It does not work by copy paste. You have to install via CocoaPods standard method by running `pod install`. lol
