### ISSUE TITLE
When keyboard appears, navigation bar steps on status bar. 

### ISSUE THREAD

**Issue by jlubeck** [hackiftekhar/IQKeyboardManager#500]
Have a look at this screen:

![Image](https://monosnap.com/file/3n4sMH439UrhbV1Oi0vzxRu2YbG3kl.png)

**Comment by hosven** [comment]
same problem

**Comment by hackiftekhar** [comment]
You all know, this can't be handled with library, because if you implement your own solution then you'll also get this issue.

**Comment by jlubeck** [comment]
What do you mean?

**Comment by hackiftekhar** [comment]
I mean this can't be handled by library because library doesn't know if status bar is overlapping with ViewController's content. library also doesn't know when to hide/show status bar and what is users requirement and what they need.

**Comment by jlubeck** [comment]
But it's not the view controller content that is overlapping, is the Navigation Bar. And it's a standard navigation bar, nothing fancy. If you see Apple Apps, when the keyboard comes into view, the viewcontroller contents go under the navigation bar, and the navigation bar stays fixed.

If you say you can't change anything in the library, can you at least give me some ideas on how can I fix it on my side? What to check? Does the library post some notifications that I can use and force the navigation bar to stay fixed no matter what? 

Thanks a lot for the library though. It's awesome and I use it in all my projects!

**Comment by jlubeck** [comment]
Ok, I don't know if this was the right way to do it, but at least it's good enough for my own application. 
@hosven see if it helps you too.

I'm basically hiding the status bar when I start editing the bottom most textfield (which was giving me the issue)

Si this is what I added to the ViewController:
```
-(void)textFieldDidBeginEditing:(UITextField *)textField{
    if(textField == self.txtNumberType){
        self.isStatusBarHidden = YES;
        [UIView animateWithDuration:0.25 animations:^{
            [self setNeedsStatusBarAppearanceUpdate];
        }];
    }
}

-(void)textFieldDidEndEditing:(UITextField *)textField{
    if(textField == self.txtNumberType){
        self.isStatusBarHidden = NO;
        [UIView animateWithDuration:0.25 animations:^{
            [self setNeedsStatusBarAppearanceUpdate];
        }];
    }
}

-(BOOL)prefersStatusBarHidden{
    return self.isStatusBarHidden;
}

-(UIStatusBarAnimation)preferredStatusBarUpdateAnimation{
    return UIStatusBarAnimationSlide;
}
```

If you find a better way, let me know...

**Comment by hackiftekhar** [comment]
You can put all your content inside a UIScrollView, so library just scroll the scrollView and will not move whole UIView. This is the easiest way you can fix this issue.

**Comment by jlubeck** [comment]
Nope, the content is already in a UIScrollView, and it was still doing this behavior

**Comment by hackiftekhar** [comment]
Are you using UINavigationController as container or you directly added UINavigationBar?

**Comment by jlubeck** [comment]
UINavigationController

**Comment by hackiftekhar** [comment]
It's working as expected in my demo. If it's not working fir you then please share demo project.

**Comment by boai** [comment]
Demo wrote a little mess, for example: there are navi will push navi, sometimes block input box, these problems in your demo no problem, but you did not say how to solve this problem!

**Comment by hackiftekhar** [comment]
Then Could you please share a demo project where I can find the problem and will try to fix that?

**Comment by boai** [comment]
OK! I wrote to you git address!

**Comment by hackiftekhar** [comment]
@boai Have you wrote a demo yet?

**Comment by hackiftekhar** [comment]
@boai any updates for demo project?

**Comment by hackiftekhar** [comment]
@boai I didn't find any demo in my mailbox. Are you sure you sent me a demo?

**Comment by arunpandiyanp** [comment]
self.view.window.windowLevel = UIWindowLevelStatusBar;

**Comment by sudhakarvarma** [comment]
@arunpandiyanp thanks for the solution. I just added this line self.view.window.windowLevel = UIWindowLevelStatusBar; and I set StatusBar background colour to same as my navigation bar colour

**Comment by catluc** [comment]
Please be aware if you are using libraries like SWViewController because IQKeyboardManger will get the top viewController that it will find. I just modify in my local the **topMostController() -> UIViewController** function of the UIView extension of this lib not to get the SWViewController but the correct controller of my view. Hope this helps!

**Comment by GuoleiYou** [comment]
Non-translucent navigation bar is pushed outside the screen #779

**Comment by hackiftekhar** [comment]
This issue has been fixed now and will be release with v6.0.0 very soon

**Comment by wkwyatt** [comment]
Thank you @hackiftekhar, could you share a branch that it is working on in the mean time?  I would like to get this working as soon as possible.

**Comment by hackiftekhar** [comment]
It's the master branch now.

**Comment by wkwyatt** [comment]
@hackiftekhar just updated to 5.0.8 and still having the issue after the keyboard is dismissed a couple of times.  

I have a view that is a background image and when the keyboard gets dismissed the background image pushes itself up and behind the navigation bar

![screen shot 2018-03-28 at 9 44 43 am](https://user-images.githubusercontent.com/13364964/38033100-30da3d56-326d-11e8-93b3-4e01e8fe1329.png)
![screen shot 2018-03-28 at 9 45 11 am](https://user-images.githubusercontent.com/13364964/38033103-3301bd2a-326d-11e8-8e9c-1c9473ca438a.png)

**Comment by arunpandiyanp** [comment]
i have one doubt ..you are using normal textfield or third party textfield or textview @wkwyatt

**Comment by wkwyatt** [comment]
@arunpandiyanp normal UITextView

**Comment by arunpandiyanp** [comment]
```
-(void) keyboardWillShow:(NSNotification *)note
{
 CGRect keyboardBounds;
        IQKeyboardManager.sharedManager.enableAutoToolbar = NO;
        
        [[note.userInfo valueForKey:UIKeyboardFrameEndUserInfoKey] getValue: &keyboardBounds];
        NSNumber *duration = [note.userInfo objectForKey:UIKeyboardAnimationDurationUserInfoKey];
        NSNumber *curve = [note.userInfo objectForKey:UIKeyboardAnimationCurveUserInfoKey];
        
        // Need to translate the bounds to account for rotation.
        keyboardBounds = [self.view convertRect:keyboardBounds toView:nil];
        
        // get a rect for the textView frame
        CGRect containerFrame = self.view.frame;
        containerFrame.origin.y = self.view.bounds.size.height - (keyboardBounds.size.height + containerFrame.size.height);
        // animations settings
        [UIView beginAnimations:nil context:NULL];
        [UIView setAnimationBeginsFromCurrentState:YES];
        [UIView setAnimationDuration:[duration doubleValue]];
        [UIView setAnimationCurve:[curve intValue]];
        
        // set views with new info
        self.view.frame = containerFrame;
        navigationBar.view.hidden=NO;
        //keyboard scroll
        UIEdgeInsets contentInset = _scrollBackground.contentInset;
        contentInset.top = keyboardBounds.size.height-50;
        _scrollBackground.contentInset = contentInset;
        // commit animations
        self.view.window.windowLevel = UIWindowLevelStatusBar;
        [UIView commitAnimations];
}
```
```
-(void) keyboardWillHide:(NSNotification *)note
{
    NSNumber *duration = [note.userInfo objectForKey:UIKeyboardAnimationDurationUserInfoKey];
    NSNumber *curve = [note.userInfo objectForKey:UIKeyboardAnimationCurveUserInfoKey];
    
    // get a rect for the textView frame
    CGRect containerFrame = self.view.frame;
    containerFrame.origin.y = self.view.bounds.size.height - containerFrame.size.height;
    
    // animations settings
    [UIView beginAnimations:nil context:NULL];
    [UIView setAnimationBeginsFromCurrentState:YES];
    [UIView setAnimationDuration:[duration doubleValue]];
    [UIView setAnimationCurve:[curve intValue]];
    
    // set views with new info
    self.view.frame = containerFrame;
    
    UIEdgeInsets contentInsets = UIEdgeInsetsZero;
    _scrollBackground.contentInset = contentInsets;
    _scrollBackground.scrollIndicatorInsets = contentInsets;
    self.view.window.windowLevel = UIWindowLevelNormal;
    
    // commit animations
    [UIView commitAnimations];
}

```

  ```
 [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(keyboardWillShow:)
                                                     name:UIKeyboardWillShowNotification
                                                   object:nil];
    
        [[NSNotificationCenter defaultCenter] addObserver:self
                                              selector:@selector(keyboardWillHide:)
                                                   name:UIKeyboardWillHideNotification
                                                 object:nil];
```

I don't no..this procedure is right or wrong in IQKeyboardmanager. I faced this problem one time. I open keyboard like this.

**Comment by hackiftekhar** [comment]
That's why I suggest to use master branch code for now until I release 6.0.0. I'm planning to release this around 12th April and expecting to get some new issues from developer community and we can fix them and will push this release on time with less bugs.

**Comment by wkwyatt** [comment]
THX!  Master branch works great! @hackiftekhar 

May need to update the readMe to this line though to activate
`IIQKeyboardManager.shared.enable = true`

**Comment by hackiftekhar** [comment]
There is a migration document to migrate to v6.0.0, this is written there. However you are correct. I'll need to update Readme code example.

**Comment by TomasHardy** [comment]
whole content got to top when use IQkeyboardmanager without using uiscrollview....

![simulator screen shot - iphone x - 2018-09-20 at 18 32 27](https://user-images.githubusercontent.com/16434201/45820573-b6408280-bd04-11e8-940c-2d6bfb2d3baf.png)
![simulator screen shot - iphone x - 2018-09-20 at 18 32 44](https://user-images.githubusercontent.com/16434201/45820576-b9d40980-bd04-11e8-8035-57f0da3a3013.png)

**Comment by Manibhushan393** [comment]
same issue @TomasHardy ,, i am facing , can help anyone?

**Comment by ankitjaiswal1994** [comment]
IQKeyboardManager.sharedManager().canAdjustAdditionalSafeAreaInsets = true

Adding this resolved my problem.

**Comment by karthisiva** [comment]
Yes tried it nothing helps and that property not available in 6.2.0

**Comment by hackiftekhar** [comment]
This property has been removed because we handled it automatically for you. However if you aren't using standard UINaviagationController and implementing your own solution for showing navigation bar type of UI then you will have to write some workaround to overcome this situation.

Regarding chat UI kind of pages, it's a special case where the library cannot handle all the scenarios, so I would suggest to disable library in Chat kind of controllers.

**Comment by SparklingAir** [comment]
Hello! I have standard navigation bar created by UINavigationController and it pushed up by IQKeyboardManager (ver 6.5.2)  I'm sorry, but I still do not understand from the comments - is this normal behavior? I did not see any flags in the library that can be set so that the navigation bar does not go upstairs. If I have to take some actions so that the navigation bar does not go up, then please tell me which ones.

**Comment by hackiftekhar** [comment]
please use UIScrollView @SparklingAir. It will probably stop moving UINavigationController's bar up.

**Comment by jujdu** [comment]
@hackiftekhar I've changed it from tableView to ScrollView and it still move up the whole view sometimes. I've figured out that code from line 1379 to 1401 do it. Will be pleasure if you fix it.

**Comment by dclcs** [comment]
I have same problem how to solve it
