### ISSUE TITLE
You git deleted old files causing anyone using a previous build to fail

### ISSUE THREAD

**Issue by eclair4151** [hackiftekhar/IQKeyboardManager#542]
iqkeyboardmanager.swift along with many other files were git deleted and uploaded as a new file in 4.0.4. This causes anyone with a specific pod of git version before 4.0.4 to have the files deleted if you are not on the latest version. i cant update to xcode 7.3 so i need v4.0.0 but getting that from the pod file or even manually git pulling results in a basicly empty folder. in the root folder there is no iqkeyboardmanager the only file is
IQKeyboardManager.swift.REMOVED.git-id
which is empty. Any way you could fix that so pulling older versions gives you correct files?

**Comment by hackiftekhar** [comment]
I was experimenting today with https://rtyley.github.io/bfg-repo-cleaner to reduce repo size. And it's caused by this. I'll try to fix it by tomorrow.

**Comment by hackiftekhar** [comment]
Restored tags manually. I think this should fix the issue.

**Comment by eclair4151** [comment]
It works if you do a git clone and then do a manual 
git reset --hard v4.0.0 
and then import the folder into xcode it works  but doing 

pod 'IQKeyboardManagerSwift', '4.0.0'
still results in a broken library

**Comment by hackiftekhar** [comment]
Could you please try with pod update once? Because at first time CocoaPods create a local copy of the library repo. Either you need to delete that copy from local storage or try with pod update once?

**Comment by hackiftekhar** [comment]
btw, I restored the original commit to the tags. So I think this will no longer be an issue.

**Comment by eclair4151** [comment]
Nope still cant put any version. manually deleted the folder and it was still all messed up on anything lower than 4.0.4. try it, go to a project and add 
pod 'IQKeyboardManagerSwift', '4.0.0'

**Comment by macfanatic** [comment]
This is still an issue. We're still using version `3.2.4` (I know, old) but point being if you just go download the tag from github as a ZIP or TAR and inspect the contents, you see the `IQKeyboardManager.REMOVED.git-id` still in the repo.  I checked a couple releases behind 3.2.4 and that was the case for all of them.

Totally broke this for us :(

<img width="593" alt="screen shot 2016-07-13 at 9 19 43 am" src="https://cloud.githubusercontent.com/assets/162970/16804812/8be6d89e-48db-11e6-82f0-978b96ed3ea2.png">

* https://github.com/hackiftekhar/IQKeyboardManager/releases/tag/v3.2.4
* https://github.com/hackiftekhar/IQKeyboardManager/releases/tag/v3.2.3

**Comment by hackiftekhar** [comment]
Now I forced updated all the old tags from the beginning. So you'll be able to download any tags you want without any issues. Thanks :)

**Comment by macfanatic** [comment]
Thanks, downloading 3.2.4 tag via Github includes the file correctly now so presumably will fix installing via cocoapods as well, after clearing the cache.

**Comment by hackiftekhar** [comment]
hmm, yes.
